### ISSUE TITLE
what is version of pangolin ? 

### ISSUE THREAD

**Issue by nikepakou** [HeYijia/svo_edgelet#1]
sudo make install pangolin error,
下载/Pangolin-0.4/build$  sudo make install
[sudo] password for ouweiqi: 
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != ((void *)0)' failed!
make: *** [cmake_check_build_system] 错误 127

appreciate you help me .

**Comment by HeYijia** [comment]
Sorry, I forget what version I have installed. But, I think you can follow the install instruction from [pangolin github](https://github.com/stevenlovegrove/Pangolin) to install the newest version of pangolin. It should be work in my project.

**Comment by nikepakou** [comment]
ThankU, I have resolved the problem. I don't have to run 'make install'.
