### ISSUE TITLE
轨迹信息

### ISSUE THREAD

**Issue by jixiedaima** [HeYijia/svo_edgelet#11]
可以获取它的轨迹信息吗，想与真实轨迹信息做一下对比实验？

**Comment by jixiedaima** [comment]
![test](https://user-images.githubusercontent.com/15714545/36069575-7b8ed4b0-0f27-11e8-85fd-094eaa6cc248.png)
I add some code in  it,
![test1](https://user-images.githubusercontent.com/15714545/36069587-a2f14ee8-0f27-11e8-8fe6-83369b2bb0f4.png)
but the result is not good !

**Comment by HeYijia** [comment]
Your code is wrong.  you need to save T_f_w.inverse( ).translation( ), not T_f_w.translation( ) .

**Comment by jiazhibo** [comment]
If I want to get the quaternion of the pose,should I save :
Eigen::Quaterniond q=vo_->lastFrame()->T_f_w_.rotation_matrix() ?

**Comment by HeYijia** [comment]
Eigen::Quaterniond q_fw (vo_->lastFrame()->T_f_w_.inverse().rotation_matrix() );

**Comment by jiazhibo** [comment]
Thank you for your reply
Howerer how to output timestamp still puzzles me
When I output

```
# vo_->lastFrame()->timestamp_
```
The result is 35.81 ,but the time is 181 seconds.
![data](https://user-images.githubusercontent.com/28798630/42161295-f6d3cf08-7e2c-11e8-92d5-ad98202b199b.png)
This is the comparison of results and groundtruth.
Can you tell me how to solve this problem?
