### ISSUE TITLE
请问怎么运行？

### ISSUE THREAD

**Issue by PengshuaiChai** [HeYijia/svo_edgelet#12]
实在是门外汉。课题里面又用到了视觉里程计。想问一下。
编译生成可执行文件后，euroc飞行数据也下了（mav0），运行命令是什么呢？

比如
       ./test_pipel_euroc  , 后边儿应该怎样加上要运行得数据呢？
![image](https://user-images.githubusercontent.com/34823274/37128299-763d6f30-22b4-11e8-99d9-3f47ed2215bf.png)

**Comment by HeYijia** [comment]
修改下test_pipel_euroc里的图像文件路径，然后使用./test_piple_euroc运行。

**Comment by PengshuaiChai** [comment]
谢啦，库程序跑完了。找了usb摄像机，已经利用test_live_vo调出来了影像。我想问三个应用问题。
1：能不能一边儿录像一边儿出轨迹图？你的test_live_vo程序只是调出来视频。然后没有保存成照片。是不是需要自己保存图片，然后线下自己再按照test_pipel_euroc的方式跑程序？
2：能不能够出姿态信息？

**Comment by PengshuaiChai** [comment]
你好。我拿着实验室的usb鱼眼镜头试了一下程序，然后轨迹路线会跑飞。是由于相机标定不准的原因吗？
我想问一下，相机的参数具体是什么含义。（图中do,d1,d2,d3,d4）

**Comment by PengshuaiChai** [comment]
你好。我拿着实验室的usb鱼眼镜头试了一下程序，然后轨迹路线会跑飞。是由于相机标定不准的原因吗？
我想问一下，相机的参数具体是什么含义。（图中do,d1,d2,d3,d4）
<img width="249" alt="_20180311154134" src="https://user-images.githubusercontent.com/34823274/37250973-0013b562-2543-11e8-9d04-8b1fc534d84b.png">
<img width="461" alt="_20180311154144" src="https://user-images.githubusercontent.com/34823274/37250975-009548f2-2543-11e8-9c5b-8c26d9bb14ba.png">

**Comment by PengshuaiChai** [comment]
另外，我想问一下。在做实时实验时，轨迹会丢失（抽搐）。请问您之前遇到过这种情况吗？是特征点跟踪丢失还是晃动太厉害？实时做实验时，需要注意什么吗？

**Comment by QMonteCarlo** [comment]
鱼眼睛头需要特殊的校准，而且必须特别精确才行，不能使用普通pinhole模型

**Comment by Rowchen** [comment]
请问这个链接里的vo2半稠密是没有开源吗（https://blog.csdn.net/heyijia0327/article/details/61682150）

**Comment by HeYijia** [comment]
> 请问这个链接里的vo2半稠密是没有开源吗（[https://blog.csdn.net/heyijia0327/article/details/61682150）](https://blog.csdn.net/heyijia0327/article/details/61682150%EF%BC%89)

是的, ,没开源.
