### ISSUE TITLE
test_live_vo error

### ISSUE THREAD

**Issue by zxp771** [HeYijia/svo_edgelet#15]
hi @HeYijia @supersheepcy
when I run the test_live_vo
there will occur a error like:HIGHGUI ERROR:libv4l unable to ioctl S_FMT
I use the inter aero RTF drone as the platform.
the drone has the intel realsense R200 and a facedown camera on the bottom of the drone.
I want to test this program on both of the camera.
the opencv version is :2.4.13.6
Do anyone have method for this?

**Comment by HeYijia** [comment]
I think you can solve this problem by Google. good luck.

**Comment by zxp771** [comment]
Hi @HeYijia 
Thanks for your reply.
I have one more question.
as I said before the drone have two different camera I'm wondering that if I can chose one of them by modified your code?what part should I read and modified?
Thanks for your sharing.

**Comment by HeYijia** [comment]
If you unfamiliar with computer vision, you can test my code with a usb camera first. I think my code can run directly with it.

**Comment by zxp771** [comment]
Thanks for your help.
Does it works for the camera on laptop?
I plan to test your algorithm on the drone.
In fact i'm not very familiar with computer vision.
could you please tell me which part should i modified by myself?
Thanks for your patience and sharing.

**Comment by HeYijia** [comment]
Hum, I think you need to know how to read camera image by OpenCv.  Then just check my code test_live_vo.cpp and you will find it.

**Comment by zxp771** [comment]
@HeYijia 
Thanks for your patience and help.
