### ISSUE TITLE
 svo::findEssentialMat(x1, x2, focal, pp, CV_RANSAC, 0.99, 2.0/focal_length, cv::noArray() );

### ISSUE THREAD

**Issue by zxp771** [HeYijia/svo_edgelet#16]
sorry to disturb you.
I want to modify the svo code(on ros) with your code.
but I have a problem with the “svo::findEssentialMat” in five-point.cpp

my kinetic use opencv in version of 3.3.1
when I compile the code it will occur an error in"cv::Mat(tempMask).setTo(true);"
it said:"no matching function for call to 'cv::mat::mat(cvmat*&)'"
Dose this error caused by the version of opencv?
Could you please tell me if I can modified it by using other method?
Thanks for your sharing and patience.

**Comment by sherifsas** [comment]
@zxp771 hey, I have the same issue, could you please tell me what you did to fix it. Thanks in advance.
