### ISSUE TITLE
KITTI数据集出现段错误？定位错误在在fast检测里，faster_corner_detect_10<false>(img, img_width, img_height, img_stride, barrier, corners);这个函数错误，请问是怎么回事？

### ISSUE THREAD

**Issue by zjtde1990** [HeYijia/svo_edgelet#18]

**Comment by HeYijia** [comment]
可能图像尺寸和图像金字塔的关系？图像金字塔是整数像素吗？

**Comment by zjtde1990** [comment]
我也发现了可能是图像尺寸的问题。图像是1266*370的，如果我把金字塔层数改为2层，仍然会出现段错误。但是如果，我手工将图像改成1216*368，金字塔层数是3层，就不会报错。实在不知道是什么问题，该怎样改，能不能指导一下？感谢~~

**Comment by HeYijia** [comment]
可以把图像尺寸改为 1264 × 368. 这样横轴（左右）和纵轴（上下）各丢掉一个像素（用opencv roi），相机内参数也可以近似认为不变，不需要改动，而图像尺寸又正好符合是2的倍数项。

**Comment by programmer-paul** [comment]
其实是创建金字塔那块有个bug, 导致输入图像是奇数列时，下采样后图像会错位，你们可以把下采样后的图像显示出来看看就知道了。看完bug 就很好解了

**Comment by HeYijia** [comment]
好的，没其他问题，我把这个 issue 关闭了。

**Comment by zjtde1990** [comment]
已经找到问题了，非常感谢！

**Comment by nuaayxy** [comment]
> 其实是创建金字塔那块有个bug, 导致输入图像是奇数列时，下采样后图像会错位，你们可以把下采样后的图像显示出来看看就知道了。看完bug 就很好解了

最后这个怎么解决的？
