### ISSUE TITLE
some errors

### ISSUE THREAD

**Issue by SiuKeungm** [HeYijia/svo_edgelet#2]
Hi,
There are some errors when I ran it,I can't find solutions of this case.Can you tell me what's wrong with it ?Thank you!
What's your opencv version?
![2017-10-25 23 20 52](https://user-images.githubusercontent.com/26852487/32007447-240d5392-b9dc-11e7-92a7-bc87dc6c8daa.png)

**Comment by HeYijia** [comment]
I am sorry for that I forget the findEssentialMat() include in my code have the same name with opencv2 code. I will fix this bug today.

**Comment by SiuKeungm** [comment]
Thank you very much,but there are still some problems.What's the version of opencv?And I couldn't find the header file of 'internal.hpp'.

/home/daohang/svo_edgelet-master/include/precomp.hpp:52:37: fatal error: opencv2/core/internal.hpp: No such file or directory
 #include "opencv2/core/internal.hpp"
                                     ^

**Comment by HeYijia** [comment]
I use opencv2.13.  Do you use opencv3 ?

**Comment by SiuKeungm** [comment]
yes,I use opencv3.1.It seems a bit incompatible with the previous version.

**Comment by cumtchenchang** [comment]
I also encountered similar error, I use openv3.2.
c@cc-B250-HD3:~/code/svo_edgelet/build$ make
[  2%] Building CXX object CMakeFiles/svo.dir/src/feature_detection.cpp.o
/home/cc/code/svo_edgelet/src/feature_detection.cpp: In function ‘void svo::feature_detection::saveMatToCsv(cv::Mat, std::__cxx11::string)’:
/home/cc/code/svo_edgelet/src/feature_detection.cpp:28:40: error: invalid conversion from ‘const char*’ to ‘int’ [-fpermissive]
     outputFile << cv::format(data,"CSV")<<std::endl;
                                        ^
In file included from /opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/core.hpp:3214:0,
                 from /opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/opencv.hpp:52,
                 from /home/cc/code/svo_edgelet/include/svo/global.h:28,
                 from /home/cc/code/svo_edgelet/include/svo/feature_detection.h:20,
                 from /home/cc/code/svo_edgelet/src/feature_detection.cpp:17:
/opt/ros/kinetic/include/opencv-3.2.0-dev/opencv2/core/operations.hpp:371:16: note:   initializing argument 2 of ‘cv::Ptr<cv::Formatted> cv::format(cv::InputArray, int)’
 Ptr<Formatted> format(InputArray mtx, int fmt)
                ^
/home/cc/code/svo_edgelet/src/feature_detection.cpp: In member function ‘virtual void svo::feature_detection::EdgeDetector::detect(svo::Frame*, const ImgPyr&, double, svo::Features&)’:
/home/cc/code/svo_edgelet/src/feature_detection.cpp:545:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     int a = (n>edge_list.size())? edge_list.size():n;
               ^
CMakeFiles/svo.dir/build.make:302: recipe for target 'CMakeFiles/svo.dir/src/feature_detection.cpp.o' failed
make[2]: *** [CMakeFiles/svo.dir/src/feature_detection.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/svo.dir/all' failed
make[1]: *** [CMakeFiles/svo.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by supersheepcy** [comment]
您好，我遇到了和上面一样的问题，请问cv::format函数应该怎么修改呢？

**Comment by zxp771** [comment]
Hi @cumtchenchang @SiuKeungm 

Sorry to disturb you.
Have you figured out those problems in ROS kinetic(my original version opencv is 3.3.1)?
Do you implement this algorithm in ROS?

**Comment by zhangxiaoya** [comment]
@supersheepcy  opencv版本不一样，参考这里修改一下https://answers.opencv.org/question/73223/cant-create-csv-file/
