### ISSUE TITLE
检测梯度最大点

### ISSUE THREAD

**Issue by zxp771** [HeYijia/svo_edgelet#20]
贺博士打扰了，
我在自己的摄像头下（对着特征较少的环境，比如墙面理论上来说这种情况下特征点提取和edgelet提取应该十分有限）跑您的代码过程中并没有发现有检测到梯度变化最大点。
不知道是否是没有做可视化所以看不到，还是因为这部分特征始终没有参与计算。
可否麻烦您稍微讲解一下。
谢谢🙏

**Comment by HeYijia** [comment]
梯度变化大的点我就是当做的普通特征点. 没有用其他颜色标记.

**Comment by zxp771** [comment]
@HeYijia 非常感谢！

**Comment by jiazhibo** [comment]
@HeYijia 贺博士您好，请问一下，我想看一下maxgrad和fast的分布情况，我应该改哪里呢？
还有一个问题，加入edgelet和maxgrad后的效果比svo要好是否是因为特征点的数量提高所导致的呢？
谢谢贺博士
