### ISSUE TITLE
svo_edgetlet 依赖哪个版本的opencv?

### ISSUE THREAD

**Issue by WithFoxSquirrel** [HeYijia/svo_edgelet#23]

**Comment by HeYijia** [comment]
opencv2.4.x  如果要用 opencv3，需要把代码中findEssentialmatrix等函数加上其他命名空间，不然会和opencv3本身的冲突。

**Comment by WithFoxSquirrel** [comment]
谢谢~, 另外 #include <vikit/math_utils.h>  vikit 是什么依赖?

**Comment by HeYijia** [comment]
这个代码里有，svo作者自己写的。

**Comment by HeYijia** [comment]
那应该是我集成进来了，去掉了那个文件夹。
