### ISSUE TITLE
Not enough matched featrues.  Reproject process failure! 

### ISSUE THREAD

**Issue by 1394643026** [HeYijia/svo_edgelet#24]
我用tum的rgbd_dataset_freiburg3_walking_xyz数据集，从头到尾就没有成功过。。。一直显示特征点太少。

**Comment by HeYijia** [comment]
不是所有数据集都能跑，不要对单目VO抱太高希望。

**Comment by 1394643026** [comment]
那有什么比较好的视觉开源代码推荐的吗，ORB_SLAM2我已经试过了。想不通扫地机器人等已经在工业运用的视觉SLAM是什么方法。

**Comment by HeYijia** [comment]
额，都得自己针对场景优化，也得结合其他传感器信息，祝好。
