### ISSUE TITLE
Read rectification parameters

### ISSUE THREAD

**Issue by xlong0513** [HeYijia/svo_edgelet#26]
![question](https://user-images.githubusercontent.com/35829321/65668705-c9530480-e074-11e9-94a9-480ad23aadbb.png)

请问这几个参数是什么，MH_05 数据集里好像没有这个文件。

**Comment by HeYijia** [comment]
这个是双目的参数，opencv stereorectify 部分的参数可以关注下，就能知道了。

**Comment by xlong0513** [comment]
谢谢贺博。但是数据集里并没有EuRoC.yaml这个文件，您是怎么得到这个的

**Comment by HeYijia** [comment]
自己用 opencv 生成的。
