### ISSUE TITLE
Is this equivalent to SVO2.0 in  terms of forward facing camera performance?

### ISSUE THREAD

**Issue by manojsharma221** [HeYijia/svo_edgelet#37]
As it is mentioned in the changelog that new KeyFrame selection criteria as well as automatic selection of E and H matrix is added. Are these chances equivalent to that in SVO2.0 which allows SVO to work on forward facing cameras as well ?
Looking forward to an answer. Thank You!

**Comment by HeYijia** [comment]
We have not compared the performance with the official SVO2.0.
The official implementation of SVO2.0 : https://github.com/uzh-rpg/rpg_svo_pro_open

**Comment by manojsharma221** [comment]
Thank you for your response. I might probably do the comparison in future and will post my findings here if I do so. Might help someone. Closing the issue for now.
