### ISSUE TITLE
小边原理

### ISSUE THREAD

**Issue by lizhihuit** [HeYijia/svo_edgelet#4]
用的是小边吗？小边用的哪个啊，有什么讲小边原理的教材可以看吗？还有为什么对着白墙可能检测出来呢，麻烦前辈指教

**Comment by HeYijia** [comment]
小边的原理请仔细阅读svo2.0的论文。对着白墙可能有特征那是因为我程序里做了三类检测，先检测fast角点，再检测小边，如果还没达到指定的特征点数目，会检测梯度最大点。

**Comment by lizhihuit** [comment]
哦哦，好的谢谢。那就是说您这里结合了点特征和直接法，然后又加了小边检测，目的就是在半结构话的环境中也能更好地估计相机位姿，这样理解可以吗

**Comment by HeYijia** [comment]
恩，是的。

**Comment by lizhihuit** [comment]
谢谢。那请问这样做又什么隐患吗？
