### ISSUE TITLE
always fail on kitti dataset and tum dataset

### ISSUE THREAD

**Issue by CanCanZeng** [HeYijia/svo_edgelet#9]
您这里提供的代码在Kitti数据集和TUM 数据集里面基本上都是初始化之后过几帧就挂掉了,很快就跟踪的点数目不够了,请问是我哪里配置不对吗?我测试的是KITTI里面第一个序列还有TUM中fr1_room那个序列.不过fr1_xyz那个序列是可以成功跟踪的.

**Comment by HeYijia** [comment]
kittis数据集图像尺寸不一样，图像栅格的尺寸，图像金字塔等参数都要修改。TUM数据集也不是都能跑成功，这个加了edgelet的算法并不是万能的，目前还有策略可以较高的提升算法鲁棒性。你要注意的一点是SVO的三维点收敛太慢了，要求太严格了。是不是非得收敛才能用，收敛到啥程度就能用，深度滤波器参数非得作者那么设计等都可以探究下。祝好运。

**Comment by CanCanZeng** [comment]
好的,谢谢解答.您说的这些我也知道,我就是想知道是不是在其他人电脑上也会这么容易失败,我怕是我哪里设置的不对.我也正准备好好探究一下这里面的参数设置的.
